### ISSUE TITLE
Add proper building setup that allows to use SASS

### ISSUE THREAD

**Issue by vortex6688** [usb777/AdviceNyc#2]
- Create package.json document
- install Gulp.js
- add sass compiler
- add imagemin task (to automatically reduce image size without reducing it's quality)
- update README for the repo

**Comment by usb777** [comment]
I make it during the day, thank you

2017-06-25 13:34 GMT-04:00 Matvey Kuzovkin <notifications@github.com>:

**Comment by vortex6688** [comment]
I'm working on it already, i'll create a pr and you'll need to review the code, if you will not like something, we can always add a few fixes...

That would be faster if i do this one, coz i already have it ready from a previous project, just need to update a few things

**Comment by usb777** [comment]
Ok, little later

2017-06-25 11:08 GMT-07:00 Matvey Kuzovkin <notifications@github.com>:

**Comment by usb777** [comment]
Mat, I can add you in team of this site developer - ABout US . Write for me
 your position. ME - CEO, programmer,SEO


2017-06-25 11:49 GMT-07:00 Samoila Dzmitry <dzsamoila@gmail.com>:

**Comment by vortex6688** [comment]
I don't know, just make something up... whatever you write, it will be fine

**Comment by usb777** [comment]
Man, Think and write it! Whatever for me)



2017-06-25 11:53 GMT-07:00 Matvey Kuzovkin <notifications@github.com>:

**Comment by vortex6688** [comment]
ok, i'll do a bit later, want to finish with the gulp first
